# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build and get link"
  lane :internal_link do
    gradle(task: "clean bundleRelease")
    upload_to_play_store_internal_app_sharing
  end

  desc "Submit a new Internal Testing Build to Google Play"
  lane :internal do
    gradle(task: "bundleRelease")
    upload_to_play_store(track: 'internal')
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    increment_version_code_in_properties_file(
         key: "VERSION_CODE",
         path: "./wear/versions.properties"
       )

    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end

  lane :screenshots do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    capture_android_screenshots(
        locales: ["en-US"],
        clear_previous_screenshots: true,
        app_apk_path: "./wear/build/outputs/apk/debug/rememberwear-debug.apk",
        tests_apk_path: "./wear/build/outputs/apk/androidTest/debug/rememberwear-debug-androidTest.apk",
        device_type: "wear",
        test_instrumentation_runner: "com.google.wear.soyted.junit.CustomTestRunner",
        use_tests_in_packages: "com.google.wear.soyted.fastlane",
        skip_open_summary: false
    )
    git_add(path: "./fastlane/metadata")
  end

  lane :increment do
    increment_version_code(
          gradle_file_path: "wear/build.gradle.kts",
          #ext_constant_name: "test"
          #app_folder_name:"app"
    )
  end
end
